# Generated by Django 4.2.20 on 2025-04-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_place_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yemek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
            ],
            options={
                'db_table': 'yemek',
                'managed': True,
            },
        ),
    ]
