# Generated by Django 4.2.20 on 2025-04-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chernovik', '0002_place_price_level_place_rating_place_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='types',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
