# Generated by Django 4.2.20 on 2025-04-21 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chernovik', '0006_place_lat_place_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chernovik.place'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chernovik_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chernovik.comment'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chernovik_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='chernovik-comment',
        ),
        migrations.AlterModelTable(
            name='place',
            table='chernovik-place',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='chernovik-vote',
        ),
    ]
