# Generated by Django 4.2.20 on 2025-04-29 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chernovik', '0007_alter_comment_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chernovik.place'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chernovik.comment'),
        ),
    ]
